"""Add to_dict test history

Revision ID: 83a61a5a0c4e
Revises: 0e0f6321b625
Create Date: 2024-11-18 16:35:20.562865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a61a5a0c4e'
down_revision: Union[str, None] = '0e0f6321b625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
