"""Add WebElementData model

Revision ID: fcd31c9f40ed
Revises: 
Create Date: 2024-11-12 05:08:58.489157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcd31c9f40ed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_element_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2083), nullable=False),
    sa.Column('xpath', sa.String(length=500), nullable=False),
    sa.Column('attribute', sa.String(length=100), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('selenium_script', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('selenium_script', 'status',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('web_element_data')
    # ### end Alembic commands ###
